// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ssaSingleStochKit2RInterface
void ssaSingleStochKit2RInterface(Rcpp::List StochKit2Rmodel, std::string outputFileNameString, double startTime, double endTime, unsigned int seed);
RcppExport SEXP StochKit2R_ssaSingleStochKit2RInterface(SEXP StochKit2RmodelSEXP, SEXP outputFileNameStringSEXP, SEXP startTimeSEXP, SEXP endTimeSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::List >::type StochKit2Rmodel(StochKit2RmodelSEXP );
        Rcpp::traits::input_parameter< std::string >::type outputFileNameString(outputFileNameStringSEXP );
        Rcpp::traits::input_parameter< double >::type startTime(startTimeSEXP );
        Rcpp::traits::input_parameter< double >::type endTime(endTimeSEXP );
        Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP );
        ssaSingleStochKit2RInterface(StochKit2Rmodel, outputFileNameString, startTime, endTime, seed);
    }
    return R_NilValue;
END_RCPP
}
// ssaStochKit2RInterface
void ssaStochKit2RInterface(Rcpp::List StochKit2Rmodel, std::string outputDirNameString, double time, int realizations, int intervals, bool keepStats, bool keepTrajectories, bool keepHistograms, int bins, unsigned int seed, int p);
RcppExport SEXP StochKit2R_ssaStochKit2RInterface(SEXP StochKit2RmodelSEXP, SEXP outputDirNameStringSEXP, SEXP timeSEXP, SEXP realizationsSEXP, SEXP intervalsSEXP, SEXP keepStatsSEXP, SEXP keepTrajectoriesSEXP, SEXP keepHistogramsSEXP, SEXP binsSEXP, SEXP seedSEXP, SEXP pSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::List >::type StochKit2Rmodel(StochKit2RmodelSEXP );
        Rcpp::traits::input_parameter< std::string >::type outputDirNameString(outputDirNameStringSEXP );
        Rcpp::traits::input_parameter< double >::type time(timeSEXP );
        Rcpp::traits::input_parameter< int >::type realizations(realizationsSEXP );
        Rcpp::traits::input_parameter< int >::type intervals(intervalsSEXP );
        Rcpp::traits::input_parameter< bool >::type keepStats(keepStatsSEXP );
        Rcpp::traits::input_parameter< bool >::type keepTrajectories(keepTrajectoriesSEXP );
        Rcpp::traits::input_parameter< bool >::type keepHistograms(keepHistogramsSEXP );
        Rcpp::traits::input_parameter< int >::type bins(binsSEXP );
        Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP );
        Rcpp::traits::input_parameter< int >::type p(pSEXP );
        ssaStochKit2RInterface(StochKit2Rmodel, outputDirNameString, time, realizations, intervals, keepStats, keepTrajectories, keepHistograms, bins, seed, p);
    }
    return R_NilValue;
END_RCPP
}
// tauLeapingStochKit2RInterface
void tauLeapingStochKit2RInterface(Rcpp::List StochKit2Rmodel, std::string outputDirNameString, double time, int realizations, int intervals, bool keepStats, bool keepTrajectories, bool keepHistograms, int bins, unsigned int seed, int p, double epsilon, int threshold);
RcppExport SEXP StochKit2R_tauLeapingStochKit2RInterface(SEXP StochKit2RmodelSEXP, SEXP outputDirNameStringSEXP, SEXP timeSEXP, SEXP realizationsSEXP, SEXP intervalsSEXP, SEXP keepStatsSEXP, SEXP keepTrajectoriesSEXP, SEXP keepHistogramsSEXP, SEXP binsSEXP, SEXP seedSEXP, SEXP pSEXP, SEXP epsilonSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::List >::type StochKit2Rmodel(StochKit2RmodelSEXP );
        Rcpp::traits::input_parameter< std::string >::type outputDirNameString(outputDirNameStringSEXP );
        Rcpp::traits::input_parameter< double >::type time(timeSEXP );
        Rcpp::traits::input_parameter< int >::type realizations(realizationsSEXP );
        Rcpp::traits::input_parameter< int >::type intervals(intervalsSEXP );
        Rcpp::traits::input_parameter< bool >::type keepStats(keepStatsSEXP );
        Rcpp::traits::input_parameter< bool >::type keepTrajectories(keepTrajectoriesSEXP );
        Rcpp::traits::input_parameter< bool >::type keepHistograms(keepHistogramsSEXP );
        Rcpp::traits::input_parameter< int >::type bins(binsSEXP );
        Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP );
        Rcpp::traits::input_parameter< int >::type p(pSEXP );
        Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP );
        Rcpp::traits::input_parameter< int >::type threshold(thresholdSEXP );
        tauLeapingStochKit2RInterface(StochKit2Rmodel, outputDirNameString, time, realizations, intervals, keepStats, keepTrajectories, keepHistograms, bins, seed, p, epsilon, threshold);
    }
    return R_NilValue;
END_RCPP
}
